//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculadora2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_102653_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_102653_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_102653_html_color_codes1 {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_102653_html-color-codes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103115_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103115_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103115_html_color_codes1 {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103115_html-color-codes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_10328_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_10328_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103420_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103420_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103557_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103557_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103649_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103649_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_103839_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_103839_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_104011_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_104011_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_104135_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_104135_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_10418_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_10418_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_104216_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_104216_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_104247_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_104247_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_104325_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_104325_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91133_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91133_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91158_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91158_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91245_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91245_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91245_html_color_codes1 {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91245_html-color-codes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91349_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91349_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91415_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91415_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91754_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91754_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9178_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9178_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91836_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91836_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_91953_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_91953_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9199_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9199_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92028_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92028_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92053_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92053_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92121_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92121_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92243_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92243_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9227_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9227_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92356_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92356_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92443_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92443_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92518_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92518_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92553_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92553_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9258_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9258_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92622_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92622_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9271_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9271_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92736_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92736_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92836_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92836_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9286_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9286_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_92942_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_92942_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9295_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9295_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9537_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9537_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9612_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9612_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9646_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9646_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9720_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9720_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9757_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9757_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9836_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9836_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9836_html_color_codes1 {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9836_html-color-codes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_web_22_3_2022_9924_html_color_codes_info {
            get {
                object obj = ResourceManager.GetObject("Captura web_22-3-2022_9924_html-color-codes.info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIP {
            get {
                object obj = ResourceManager.GetObject("OIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OIP__1_ {
            get {
                object obj = ResourceManager.GetObject("OIP (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_33_26_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-33-26 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_41_33_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-41-33 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_42_39_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-42-39 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_44_23_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-44-23 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_45_30_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-45-30 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_48_12_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-48-12 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_48_45_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-48-45 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_50_13_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-50-13 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_50_13_Códigos_de_Colores_HTML1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-50-13 Códigos de Colores HTML1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_51_23_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-51-23 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_52_14_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-52-14 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_52_14_Códigos_de_Colores_HTML1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-52-14 Códigos de Colores HTML1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_56_46_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-56-46 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_57_37_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-57-37 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_19_58_25_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 19-58-25 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_03_30_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-03-30 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_03_30_Códigos_de_Colores_HTML1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-03-30 Códigos de Colores HTML1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_06_48_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-06-48 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_07_41_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-07-41 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_08_47_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-08-47 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_10_02_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-10-02 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_11_08_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-11-08 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_11_08_Códigos_de_Colores_HTML1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-11-08 Códigos de Colores HTML1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_12_38_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-12-38 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_13_31_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-13-31 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_14_34_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-14-34 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_15_59_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-15-59 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_16_49_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-16-49 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_17_33_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-17-33 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_18_32_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-18-32 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_19_58_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-19-58 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_24_44_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-24-44 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_34_24_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-34-24 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_35_53_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-35-53 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_36_19_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-36-19 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2022_03_21_at_20_36_58_Códigos_de_Colores_HTML {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2022-03-21 at 20-36-58 Códigos de Colores HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
